version: "3.3"
services:
  db:
    container_name: db
    image: sartography/cr-connect-db:$E2E_TAG
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=covid_user
      - POSTGRES_PASSWORD=covid_pass
      - POSTGRES_MULTIPLE_DATABASES=covid_test
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    container_name: backend
    depends_on:
       - db
    image: sartography/uva-covid19-testing-communicator:$E2E_TAG
    environment:
      - APPLICATION_ROOT=/
      - CORS_ALLOW_ORIGINS=localhost:4200,frontend:4200
      - DB_HOST=db
      - DB_NAME=covid_test
      - DB_PASSWORD=covid_pass
      - DB_PORT=5432
      - DB_USER=covid_user
      - DEVELOPMENT=true
      - PORT0=5000
      - PRODUCTION=false
      - TESTING=false
      - UPGRADE_DB=true
    ports:
      - "5000:5000"
    command: ./wait-for-it.sh db:5432 -t 0 -- ./docker_run.sh


#  frontend:
#    container_name: frontend
#    depends_on:
#       - db
#       - backend
#    image: sartography/uva-covid19-testing-frontend:dev
#    environment:
#      - API_URL=http://localhost:5000/api/v1.0
#      - BASE_HREF=/app/
#      - DEPLOY_URL=/app/
#      - HOME_ROUTE=home
#      - PORT0=4200
#      - PRODUCTION=false
#    ports:
#      - "4200:4200"
